### ISSUE TITLE
Exception thrown when using k-G with max degree constraint

### ISSUE THREAD

**Issue by fcole90** [mauro-idsia/blip#8]
Using solver k-G with max degree constraint makes blip crash throwing exceptions.

Try running:
`java -jar blip.jar scorer.sq -c bdeu -d data/child-5000.dat -j data/child-5000.jkl -n 3 -t 10`
and then
`java -jar blip.jar -j data/child-5000.jkl -r data/child.kg.res -t 10 -w 4 -v 1`

When I attempt it I get the following:
```
Read scores... 
Starting 0 searcher 
... Ended! 
Exception in thread "pool-1-thread-1" Num Iterations total: 0 
java.lang.NullPointerException
	at ch.idsia.blip.core.learn.solver.samp.SimpleSampler.sample(SimpleSampler.java:24)
	at ch.idsia.blip.core.learn.solver.src.brutal.BrutalOldSearcher.search(BrutalOldSearcher.java:55)
	at ch.idsia.blip.core.learn.solver.BaseSolver$BaseSearcher.run(BaseSolver.java:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Error during execution, in class: ch.idsia.blip.api.learn.solver.tw.QuietMcSolverApi
```

**Comment by mauro-idsia** [comment]
Thanks for notifying me, I'll take a look!
